# Site settings
title: "Celle où ya du sable - Yoga à Lacanau"
description: "Cours de Hatha et Yin Yoga avec Nathalie à Lacanau. Découvrez la sérénité à travers des pratiques douces et ressourçantes."
baseurl: ""
url: "https://celleouyadusable.com"
author: "Nathalie - Professeure de Yoga"
future: true

timezone: Europe/Paris
# SEO
lang: fr
locale: fr_FR

# Collections
collections:
  courses:
    output: true
    permalink: /cours/:name/
  events:
    output: true
    permalink: /evenement/:name/
  ceremonie_lune:  # Nouvelle collection dédiée
    output: true
    permalink: /ceremonie-lune/:day-:month-:year/
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_pages/accueil.md"
    values:
      layout: "accueil"
      sitemap:
        priority: 1.0
        changefreq: 'weekly'
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      sitemap:
        priority: 0.8
        changefreq: 'weekly'
  - scope:
      path: ""
      type: "ceremonie_lune"
    values:
      layout: "event"
      sitemap:
        priority: 0.8
        changefreq: 'weekly'
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
      sitemap:
        priority: 0.9
        changefreq: 'monthly'
  - scope:
      path: "contact/"
    values:
      sitemap:
        priority: 0.7
        changefreq: 'monthly'
  - scope:
      path: "temoignages/"
    values:
      sitemap:
        priority: 0.7
        changefreq: 'monthly'
  - scope:
      path: "retraites/"
    values:
      sitemap:
        priority: 0.7
        changefreq: 'weekly'
  - scope:
      path: "faq/"
    values:
      sitemap:
        priority: 0.6
        changefreq: 'monthly'
  - scope:
      path: "mentions-legales/"
    values:
      sitemap:
        priority: 0.3
        changefreq: 'yearly'
  - scope:
      path: "conditions-generales-utilisation/"
    values:
      sitemap:
        priority: 0.3
        changefreq: 'yearly'
  # Exclusions du sitemap
  - scope:
      path: "admin/**"
    values:
      sitemap: false
  - scope:
      path: "assets/**"
    values:
      sitemap: false
  - scope:
      path: "*.json"
    values:
      sitemap: false


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
excerpt_separator: "<!--more-->"
# Exclusions du sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
  - admin/
