# Site settings
title: "Celle où ya du sable - Yoga à Lacanau"
description: "Cours de Hatha et Yin Yoga avec Nathalie à Lacanau. Découvrez la sérénité à travers des pratiques douces et ressourçantes."
baseurl: ""
url: "https://celle-ou-yadusable.com"
author: "Nathalie - Professeure de Yoga"

# SEO
lang: fr
locale: fr_FR

# Collections
collections:
  courses:
    output: true
    permalink: /cours/:name/
  events:
    output: true
    permalink: /evenement/:name/
  ceremonie_cacao:  # Nouvelle collection dédiée
    output: true
    permalink: /ceremonie-cacao/:day-:month-:year/
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_pages/accueil.md"
    values:
      layout: "accueil"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "ceremonie_cacao"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
excerpt_separator: "<!--more-->"
# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
